### ISSUE TITLE
Truncated uploads when firmware size larger than 0xFFFE * TRANSFER_SIZE

### ISSUE THREAD

**Issue by jcard0na** [vitalyvb/usbd-dfu#8]
When uploading large firmware files, the upload is truncated after `0xFFFE * TRANSFER_SIZE`

When the 16-bit `req.value` field wraps around, the device will interpret that as a request for list commands and send that instead of the next block of data.  That list is 3-bytes long, which the host (`dfu-util`) interprets as end of data and terminates the upload.

This is [where this happens](https://github.com/vitalyvb/usbd-dfu/blob/main/src/class.rs#L788) in `class.rs`.

The captures below show valid request responses (128 bytes) followed by the incorrect response (67 bytes) on `req.value (wValue)` wraparound.

![image](https://user-images.githubusercontent.com/676181/233771419-34388d78-015d-470c-8a7e-5e0c91cd3a03.png)
![image](https://user-images.githubusercontent.com/676181/233771005-5d2825ec-0ba1-4348-9623-00908db71467.png)

I do not know if this is a bug, or a limitation in the DFU protocol.  Maybe it does not support large files (16MB)?

The download operation works fine.

### To repro

Just increase the size of the memory  in [the example code](https://github.com/vitalyvb/usbd-dfu#example) to
```
const MEM_INFO_STRING: &'static str = "@Flash/0x00000000/65536*256 g";
```
and try to read back with `dfu-util`

```
$ dfu-util -d f055:217f --dfuse-address 0 -U readback8.rom
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
Device ID f055:df11
Device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Interface #0 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 011a
Device returned transfer size 64
DfuSe interface name: "Flash"
Limiting upload to end of memory segment, 16777216 bytes
Upload	[=========================] 100%      4194179 bytes
Upload done.
```
And notice the trailing bytes at the end:
```
$ xxd readback8.rom | tail -4
003fff50: 0a00 0000 0000 0000 0000 0000 0000 0000  ................
003fff60: 0000 0000 0000 0000 0000 0000 0000 0000  ................
003fff70: 0000 0000 0000 0000 0000 0000 0000 0000  ................
003fff80: 0021 41                                  .!A
```
that correspond to 
```
                DnloadCommand::GetCommands  (0x00)
                DnloadCommand::SetAddressPointer (0x21)
                DnloadCommand::Erase (0x41)
```

**Comment by vitalyvb** [comment]
Hi @jcard0na ,

Indeed, bad things will happen when block number wraps around. I haven't seen anywhere that this case should be handled on a device side somehow, so please let me know if you'd seen something on this topic. There are ways around this limitation, though.

"USB DFU protocol used in the STM32 bootloader" document has a formula how target address is calculated, it's the same for Download and Upload:
>Address = ((wBlockNum – 2) × wTransferSize) + Addres_Pointer, where:
>
>– wTransferSize: length of the data buffer sent by the host
>– wBlockNumber: value of the wValue parameter

The same document describes the behavior for wValue == 0, it's not an address, but a command, hence "wBlockNum – 2" above, as addresses start with "wValue > 1". (note that USB DFU 1.1 is a slightly different protocol, and does not have this feature).

I think there are following ways to work this around. On a device side:
* Increase wTransferSize by adding `features = ["control-buffer-256"]` or something else to usb-device dependency and setting TRANSFER_SIZE. Transfers up to 1024 bytes are probably safe.
* Splitting a single memory region into two smaller regions. `dfu-util` should use Set Address Pointer command so set the initial address, and block number will start from "2" for each region, making it accessible.

On host side:
* If host will use Set Address Pointer command more frequently, it would be able to Download or Upload everything in one go. As I remember, `dfu-util` is using Set Address Pointer during Download (but I may be wrong here).
* Maybe manually specifying `-s` parameter with the address and length would allow Uploads in chunks.

Overall, if `dfu-util` Downloads data fine (by using Set Address Pointer command), but fails to Upload (by not using Set Address Pointer command), then it would be `dfu-util` limitation or bug.

Thanks

**Comment by jcard0na** [comment]
Hi @vitalyvb,

Thank you for the quick and detailed answer.  This was very useful:

> Increase wTransferSize by adding features = ["control-buffer-256"] or something else to usb-device dependency and setting TRANSFER_SIZE.

I did not know about that feature.  Switching to 256-byte transfers got me closer to the goal:  the transfer now truncates at 16776704 (0xfffe * 256), or just 512 bytes short. :2nd_place_medal: 

>  Transfers up to 1024 bytes are probably safe.

^This confused me because setting any transfer size larger than 256 results in an error.
```
libusb_control_transfer returned -9 (LIBUSB_ERROR_PIPE)
```
I saw that `usb-device` has another feature (`test-class-high-speed`) that supposedly uses "larger endpoint buffers", but that did not work for me, even though my host is high-speed (USB2).

So I might go with the chunked uploads.  Now that I know the root cause for this problem, it is a viable workaround.

Thanks!

**Comment by vitalyvb** [comment]
@jcard0na ,

Sorry for a confusion with transfer sizes, I thought usb-device has features for 512 and/or 1024 buffers, but it's not merged - https://github.com/rust-embedded-community/usb-device/pull/62 Still, with this patch applied and feature enabled, I believe it should work. Setting TRANSFER_SIZE to a value above the size of a buffer of usb-device definitely won't work, and there's no compile-time check.

Thanks

**Comment by jcard0na** [comment]
Oh, that makes sense.  Thanks for the help!
The problem as stated in the title of this issue seems to be more a DFU protocol limitation so I'll go ahead and close it.

**Comment by jcard0na** [comment]
By the way, @vitalyvb, I just tried applying https://github.com/rust-embedded-community/usb-device/pull/62 manually and the `control-buffer-1024` feature work very well.  I can now upload without truncation the full 16MB firmware.  And as a bonus, the total firmware upgrade time has been reduced by a factor of 6.  Thank you again! :vulcan_salute:
